- LICENSE
- README.md
- src/README.md
- src/types.ts
This create a README for the Checkpoint project and provides relevant
links to the Checkpoint documentation.
> chore: wrap up readme and license

- package.json
* make sortBy fields a graphql enum ([#37](https://github.com/snapshot-labs/checkpoint/issues/37)) ([a63f06a](https://github.com/snapshot-labs/checkpoint/commit/a63f06a51c39153b8a135f58069031753cd97ab3))
* writers type for block ([#25](https://github.com/snapshot-labs/checkpoint/issues/25)) ([8547d89](https://github.com/snapshot-labs/checkpoint/commit/8547d89cb0337f5e317f76b21bc331b5ce9a6f46))
* configure starknet provider url ([#36](https://github.com/snapshot-labs/checkpoint/issues/36)) ([e5413ca](https://github.com/snapshot-labs/checkpoint/commit/e5413cae9b02df0f966304eab032a18400e75579))
* generate sample query in graphiql ([#35](https://github.com/snapshot-labs/checkpoint/issues/35)) ([a151239](https://github.com/snapshot-labs/checkpoint/commit/a151239f0d107f0b831e75475e63e3c9da9bfb84 …
> release: v0.1.0-beta.1

- src/checkpoint.ts
> fix: declare tx type

- src/types.ts
> Make deploy_fn optional

- package.json
- src/checkpoint.ts
- yarn.lock
RPC 0.2.1 changes pagination format so we need to update the code to be compatible with latest RPC servers.
> feat: add rpc 0.2.1 compatibility

- src/graphql/controller.ts
Closes: https://github.com/snapshot-labs/checkpoint/issues/165
Adds `Boolean` type support.
- In checkpoint-template add field with `Boolean` type: `visibile: Boolean`.
- Start the server.
> feat: add Boolean field support

- .github/workflows/build-test-release.yml
- .github/workflows/build-test.yml
- .github/workflows/release.yml
This way we can have tests trigger automatically if we have PR coming from a fork.
> chore: run CI for pull requests from forks

- src/checkpoint.ts
This PR adds validation on config:
- Checking if all used Abis were passed
- Checking if all used writers are defined
- Rename writer in config/writers file. It should complain.
- Rename abi in config/opts. It should complain.
> feat: add config validation (abis, writers)

- src/graphql/controller.ts
- test/unit/graphql/__snapshots__/controller.test.ts.snap
After knex conversion we are missing primary key for `id` column.
> fix: add primary key for id

- package.json
Release to include two bug fixes in latest version:
- https://github.com/checkpoint-labs/checkpoint/commit/0c5c50463fd88566c7f1ea6d1096072926c6e6a5
- https://github.com/checkpoint-labs/checkpoint/pull/219
> release: v0.1.0-beta.17

- src/checkpoint.ts
- src/types.ts
This PR adds fetchInterval option to change default interval.
> feat: add fetchInterval option

- package.json
- src/checkpoint.ts
- src/schemas.ts
- src/types.ts
- yarn.lock
Closes: https://github.com/checkpoint-labs/checkpoint/issues/11
- Start sx-api - it works
- Do some change in config.json, remove non-optional property, change type of value (add `// @ts-ignore` to make it compile).
- Start sx-api, you get error
> feat: validate checkpoint config with zod

- package.json
- src/providers/starknet/index.ts
- src/providers/starknet/utils.ts
- src/types.ts
- test/unit/providers/starknet/__snapshots__/utils.test.ts.snap
- test/unit/providers/starknet/fixtures.ts
- test/unit/providers/starknet/utils.test.ts
- yarn.lock
This PR adds support for parsing events with Cairo1 ABIs.
Tests should pass, it tests both Cairo0 and Cairo1 events.
> feat: parse Cairo1 events

- package.json
Contains changes needed to convert sx-api to ORM.
> release: v0.1.0-beta.21

- src/orm/model.ts
Closes: https://github.com/checkpoint-labs/checkpoint/issues/249
> fix: do not return null for all falsy values

- src/codegen.ts
- src/graphql/controller.ts
- src/orm/model.ts
- test/unit/__snapshots__/codegen.test.ts.snap
Closes: https://github.com/checkpoint-labs/checkpoint/issues/248
- Change your id to `Int!` and run codegen with `node ../checkpoint/dist/src/bin/index.js generate`.
> feat: support both String and Int entity IDs

- package.json
To be merged once those are merged:
- https://github.com/checkpoint-labs/checkpoint/pull/261
- https://github.com/checkpoint-labs/checkpoint/pull/262
> release: v0.1.0-beta.23

- src/graphql/controller.ts
Closes: https://github.com/checkpoint-labs/checkpoint/issues/267
> fix: ensure subentities are defined in where type

- src/providers/starknet/index.ts
getPendingTransactions was removed
> fix: replace getPendingTransactions with getBlockWithTxs

- src/checkpoint.ts
Previously if we encountered exception there it could result in entire app crashing.
> fix: handle exceptions in nextEvents

- src/graphql/resolvers.ts
Follow up to: https://github.com/checkpoint-labs/checkpoint/pull/287
Forgot to commit this change before merging.
> fix: resolve inner join columns with non-derived list fields

- package.json
Release PR for https://github.com/checkpoint-labs/checkpoint/pull/290
> release: v0.1.0-beta.33

- src/checkpoint.ts
- src/providers/base.ts
- src/providers/evm/provider.ts
- src/providers/starknet/provider.ts
- src/providers/starknet/types.ts
- src/stores/checkpoints.ts
- test/unit/stores/__snapshots__/checkpoints.test.ts.snap
This PR aims to handle reorgs where they are detected and addressed by rolling back data.
Closes: https://github.com/snapshot-labs/workflow/issues/28
- Apply diff from below (adds support for Blast API and increases interval to catch reorgs)
- Run checkpoint-template `sekhmet/evm` branch with Gnosis Chain API and pretty fresh block.
- Wait for reorg (https://gnosisscan.io/blocks_forked) it's gotten a bit infrequent currently.
- See logs that it was detected, resolved and handled.
```diff
diff --git a/src/checkpoint.ts b/src/checkpoint.ts
index ccba51b..248f971 100644
--- a/src/checkpoint.ts
+++ b/src/checkpoint.ts
@@ -24,7 +24,7 @@ const BLOCK_RELOAD_MIN_RANGE = 10;
const BLOCK_PRELOAD_STEP = 100;
const BLOCK_PRELOAD_TARGET = 10;
const BLOCK_PRELOAD_OFFSET = 50;
-const …
```
> feat: add reorg support

- src/bin/index.ts
- src/checkpoint.ts
- src/codegen.ts
- src/container.ts
- src/graphql/controller.ts
- src/graphql/index.ts
- src/graphql/resolvers.ts
- src/orm/model.ts
- src/providers/base.ts
- src/providers/evm/provider.ts
- src/providers/starknet/provider.ts
- src/register.ts
- src/schemas.ts
- src/stores/checkpoints.ts
- src/types.ts
- src/utils/database.ts
- src/utils/graphql.ts
- test/unit/__snapshots__/codegen.test.ts.snap
- test/unit/codegen.test.ts
- test/unit/graphql/__snapshots__/controller.test.ts.snap
- test/unit/stores/__snapshots__/checkpoints.test.ts.snap
- test/unit/stores/checkpoints.test.ts
- test/unit/utils/database.test.ts
This PR brings `next` branch changes (related to multi-chain indexing back to main branch ready for release.
Closes: https://github.com/snapshot-labs/workflow/issues/154
Included PRs:
- https://github.com/checkpoint-labs/checkpoint/pull/325
- https://github.com/checkpoint-labs/checkpoint/pull/327
- https://github.com/checkpoint-labs/checkpoint/pull/328
- https://github.com/checkpoint-labs/checkpoint/pull/329
> feat: add support for multi chain indexing

- src/graphql/resolvers.ts
Previously every non derived 1-to-N mapping would trigger separate database query.
With this change those are batched with dataloader.
For some queries (for example spaces query) it cuts down number of queries from ~20 to 3.
Those queries were made in parallel so speedup is not huge, but makes a difference and should reduce number of spikes in API response times in case of one of those 20 queries being slow.
Before:
After:
> perf: batch non-derived subentities with loader

- src/providers/evm/provider.ts
- src/providers/starknet/provider.ts
Currently if one of the requests in getCheckpointsRange fails it will cause entire preload step to recompute.
This might make preload slower if errors happen. With this change we will only retry failed requests instead of entire preload step.
> fix: do not reset preload if one request fails

- src/providers/evm/provider.ts
Previously checkpoints were not created for EVM providers. This adds this missing functionality.
Closes: https://github.com/checkpoint-labs/checkpoint/issues/355
1. Run some API using EVM provider.
2. After a while check for checkpoints.
```gql
{
_checkpoints(indexer: "sep") {
id
indexer
block_number
}
}
```
> fix: create checkpoints in EVM provider

- package.json
- src/providers/evm/provider.ts
spread puts items on the stack so it can overflow.
> refactor: remove spread operator
