src/types.ts
The previous release erronoeusly specified the type for Checkpoint
writers as a number when it is actually an object.
It also exports the checkpoint writer function.
=> fix: writers type for block

package.json, src/checkpoint.ts, src/graphql/controller.ts, src/graphql/index.ts, src/utils/graphql.ts, test/unit/graphql/__snapshots__/controller.test.ts.snap, test/unit/graphql/controller.test.ts, yarn.lock
This generats an example query based on the first defined entity in the
schema argument to Checkpoint.
Resolves #24 .
> Example screenshot from checkpoint-template.
=> feat: generate sample query in graphiql

src/graphql/controller.ts, test/unit/graphql/__snapshots__/controller.test.ts.snap
This makes the sortBy fields for multi record queries to be generated as
enums. This will also help fix a potential sql injection issues that
allows users to insert arbitrary orderBy strings in queries.
Resolves #9
=> fix: make sortBy fields a graphql enum

package.json, src/types.ts, src/utils/logger.ts
This enables synchronous logging for pino, which will ensure that log
outputs are not buffered but output instantly. This will help reduce
confusion when the writer functions are using the default console logger
or some other synchronous logger of their choice.
Resolves #60 
Also includes fix: enable pretty logging without dependency
This enables pretty logging without explicitly requiring the users of
the library to install pino-pretty.
=> fix: enable synchronous logging

.github/workflows/build-test-release.yml, src/checkpoint.ts, src/types.ts, src/utils/checkpoint.ts
This add a 2 new params for the config file `tx_fn` and `start`. Using `tx_fn` allow you to trigger a writer function for all the transactions, `start` define where to start to trigger `tx_fn` writer. Here is an example of config:
```json
{
"network": "goerli-alpha",
"start": 276000,
"tx_fn": "handleTx",
"sources": []
}
```
In the writer
```ts
export async function handleTx({ block, tx, receipt, mysql }) {
// Do stuff
}
```
Closes #62
=> Add new config tx_fn to catch any tx

src/graphql/controller.ts, src/graphql/resolvers.ts, test/unit/graphql/__snapshots__/controller.test.ts.snap, test/unit/graphql/controller.test.ts
Adds support for GraphQL list. Those are represented using `JSON` column type. Those are not indexed and can't be used in `where` for now.
- Test using sx-api PR: https://github.com/snapshot-labs/sx-api/pull/150
=> feat: add support for lists

src/checkpoint.ts, src/graphql/controller.ts, src/graphql/index.ts, src/graphql/resolvers.ts
Adds support for subqueries.
Apply this patch to `sx-api`:
```diff
diff --git a/src/schema.gql b/src/schema.gql
index e9026b1..ecd4a93 100644
--- a/src/schema.gql
+++ b/src/schema.gql
@@ -24,7 +24,7 @@ type Space {
type Proposal {
id: String!
proposal_id: Int
-  space: String
+  space: Space
author: String
execution_hash: String
metadata_uri: String
```
Run this query:
```gql
{
proposals(first: 10) {
id
proposal_id
space {
id
name
}
}
space (id: "0x00b60f2a154b9aaec8e4bec8e04f86d6cd92a9c993871e904bd815962603492d") {
id
name
}
}
```
=> feat: add support for subqueries (one-to-one)

src/graphql/controller.ts
Right now we require `id` to be String!, but it makes sense (and is common) to use `ID!`.
=> feat: allow built-in ID type as object id

src/graphql/controller.ts, src/graphql/resolvers.ts, src/utils/graphql.ts
If you make nested entity non nullable it will be wrapped in GraphQLNonNull so we need to unwrap it when using it.
- Change `author: User` to `author: User!` in sx-api's Proposal schema.
- Run query below.
```gql
{
proposals(where: {space: "0x00847ae39833c61fe964bfac857ad8c5fa261ec4c716c61b8f28c4ae61fe376b"}) {
id
title
author {
id
vote_count
}
}
}
```
=> feat: unwrap nonNull

src/checkpoint.ts, src/graphql/controller.ts, src/mysql.ts, src/stores/checkpoints.ts, src/types.ts, test/unit/__snapshots__/mysql.test.ts.snap, test/unit/graphql/__snapshots__/controller.test.ts.snap, test/unit/graphql/controller.test.ts
Closes: https://github.com/snapshot-labs/checkpoint/issues/152
This PR adds support for `BigInt` and decimal types (`Decimal` and `BigDecimal`).
Current mappings are:
- `BigInt` -> `BIGINT`
- `Decimal` -> `DECIMAL(10, 2)`
- `BigDecimal` -> `DECIMAL(20, 8)`.
Decimal types are configurable so you can provide different precision/decimals values (or add more variants):
```js
const checkpoint = new Checkpoint(config, writer, schema, {
decimalTypes: {
Decimal: {
p: 14,
d: 10
},
BigDecimal: {
p: 20,
d: 8
},
EvenBiggerDecimal: {
p: 40,
d: 16
}
}
});
```
In your schema declare types that you use (either default ones, or the ones you added) and use those in your types as needed
```gql
scalar BigInt
scalar Decimal
scalar BigDecimal
type User {
votes_count: BigInt
}  
```
When writing data pass your …
=> feat: add support for BigInt and decimal types

package.json, src/checkpoint.ts, src/types.ts, test/fixtures/checkpointConfig.fixture.ts, yarn.lock
Closes: https://github.com/snapshot-labs/checkpoint/issues/54
This PR **replaces** Sequencer with RPC for indexing.
**Limitations:**
- In latest versions of `starknet` sequencer provider doesn't return full transactions in blocks response and there is no way to opt-out of it as-is. This means we would need to add extra request to fetch every transaction in block. As of now this PR drops support for Sequencer and will work with RPC only.
- ~RPC doesn't return receipts in the block response, this means we have to query receipts manually which adds extra requests.~ solved by using `getEvents` call.
- because we use `getBlockWithTxs` + `getEvents` calls we don't have access to receipts in the responses (unless we add extra request per transaction for it) so writers no longer receive …
=> feat: use RPC instead of Sequencer

package.json, src/graphql/index.ts, src/graphql/resolvers.ts, yarn.lock
This PR adds [`dataloader`](https://github.com/graphql/dataloader) support for single queries that improves performance of nested queries. Now fetching 10 proposals with spaces nested in the query takes 2 requests instead of 20.
Closes: https://github.com/snapshot-labs/checkpoint/issues/147
Add console.log above `const results = await context.mysql.queryAsync(query, [ids]);`.
Run query:
```gql
{
proposals(first: 100) {
id
proposal_id
space {
id
name
}
}
}
```
Only single log should be emitted.
=> feat: use dataloader to batch single entity queries

src/graphql/controller.ts, src/graphql/resolvers.ts, test/unit/graphql/__snapshots__/controller.test.ts.snap
Escape column names in queries so reserved keywords can be used as columns.
Depends on https://github.com/snapshot-labs/checkpoint/pull/159
Apply this diff in sx-api
```diff
diff --git a/src/schema.gql b/src/schema.gql
index 978b787..49d5ff5 100644
--- a/src/schema.gql
+++ b/src/schema.gql
@@ -25,7 +25,7 @@ type Proposal {
id: String!
proposal_id: Int
space: Space
-  author: User
+  from: User
execution_hash: String
metadata_uri: String
title: Text
diff --git a/src/writer.ts b/src/writer.ts
index ab167a9..e79e085 100644
--- a/src/writer.ts
+++ b/src/writer.ts
@@ -74,7 +74,7 @@ export async function handlePropose({ block, tx, event, mysql }) {
id: `${space}/${proposal}`,
proposal_id: proposal,
space,
-    author,
+    from: author,
execution_hash: data.execution_hash,
metadata_uri: …
```
=> feat: escape column names

src/types.ts
We check that block has to be full block before calling writers so we can narrow it down to avoid awkward handling at writer side.
=> chore: narrow down writer's block param

src/checkpoint.ts, src/types.ts
This PR allows consumers to modify sources on the fly, when other events arrive.
Writers now receive `instance` argument, which is Checkpoint instance itself. In this case developers can use `executeTemplate` to use predefined template from config.
Closes: https://github.com/snapshot-labs/checkpoint/issues/52
Update sx-api config to:
```json
{
"network_node_url": "RPC",
"sources": [
{
"contract": "0x2121c175922cef8870b6b6b956d01a7ac75af034dfbb9135698f88644b17ea3",
"start": 345862,
"events": [
{
"name": "space_deployed",
"fn": "handleSpaceCreated"
}
]
}
],
"templates": {
"Space": {
"events": [
{
"name": "proposal_created",
"fn": "handlePropose"
},
{
"name": "vote_created",
"fn": "handleVote"
}
]
}
}
}
```
Call this function in `handleSpaceCreated`:
```js
instance.executeTemplate('Space', { …
```
=> feat: add templates support

src/checkpoint.ts, src/graphql/index.ts, src/index.ts
This allows to use checkpoint via ApolloServer (and possibly other clients).
Build checkpoint from this PR and copy files over (instead of linking, as GraphQL depends on instance equality which doesn't work when linked) to sx-api, setup ApolloServer there like this:
```js
import Checkpoint, { LogLevel, createGetLoader } from '@snapshot-labs/checkpoint';
import { ApolloServer } from '@apollo/server';
import { startStandaloneServer } from '@apollo/server/standalone';
// Same checkpoint initialization here as before.
async function run() {
const server = new ApolloServer({
schema: checkpoint.getSchema()
});
const { url } = await startStandaloneServer(server, {
listen: { port: 3000 },
context: async () => {
const baseContext = checkpoint.getBaseContext();
return {
...baseContext,
getLoader: …
```
=> feat: expose schema and createGetLoader

package.json, src/checkpoint.ts, src/types.ts, yarn.lock
4.13.1 no longer hardcodes `/rpc/v0.2` as part of URL so it's compatible with Infura.
=> chore: bump starknet to 4.13.1 to fix Infura compatibility

src/checkpoint.ts, src/providers/base.ts, src/providers/index.ts, src/providers/starknet.ts, src/types.ts
This PR moves Starknet logic out of Checkpoint class into `NetworkProvider` that becomes responsible for fetching blocks and processing them. This allows for replacing indexing logic if needed.
I'm not sure if it's enough of abstraction to implement what we want, because I'm not sure how custom DB would work ("custom db (would be used for Snapshot)" from issue description. Would that query data by blockNum as well or it needs higher abstraction - if it does, some details would be helpful for context.
Closes https://github.com/snapshot-labs/checkpoint/issues/155
- Start `sx-api`.
=> refactor: extract NetworkProvider

package.json, src/graphql/controller.ts, src/graphql/index.ts, src/graphql/resolvers.ts, src/utils/graphql.ts, yarn.lock
Closes https://github.com/snapshot-labs/checkpoint/issues/170
Uses `pluralize` to improve naive way of pluralizing queries/table names.
- In checkpoint-template rename `Post` to `Activity`. In writer changes `posts` to `activities` in SQL query.
- Start indexer.
- Run this query:
```gql
{
activities {
id
}
}
```
=> feat: use pluralize for better pluralization

src/checkpoint.ts, src/providers/starknet/index.ts, src/types.ts
Closes https://github.com/snapshot-labs/checkpoint/issues/179
This PR adds support for `globalEvents` that allows you to track specific event from all contracts.
Link this PR to checkpoint-template branch that tracks ERC20s Transfers:
https://github.com/snapshot-labs/checkpoint-template/tree/sekhmet/erc20
Run it and run this query:
```gql
{
transfers {
id
token
from
to
value,
created_at
created_at_block
}
}
```
=> feat: add globalEvents tracking

src/checkpoint.ts, src/graphql/controller.ts, src/graphql/index.ts, src/graphql/resolvers.ts, src/utils/graphql.ts
Closes https://github.com/snapshot-labs/checkpoint/issues/166
This PR adds `@derivedFrom` directive support that can be used to create 1-n queries.
Add a field on some entity that references other entity for example:
```gql
type Space {
id: String!
proposals: [Proposal]! @derivedFrom(field: "space")
}
type Proposal {
id: String!
space: Space
}
```
This will cause `proposals` to become available as part of Space schema resulting in this query to database (table name is derived from type used, column name is the field argument from directive):
```sql
SELECT * FROM proposals WHERE space IN (space.id)
```
Now such queries can be used:
```gql
{
spaces {
id
proposals {
id
tx
title
strategies
}
}
}
```
You can test it against this branch on sx-api (extra changes due to event parsing): …
=> feat: add subentities support

src/checkpoint.ts, src/types.ts
This way we can use automatic parsing of events for template-initiated contracts.
Can be tested with https://github.com/snapshot-labs/sx-api/pull/163
=> feat: allow ABI to be specified in templates

src/checkpoint.ts, src/providers/starknet/index.ts, src/types.ts
Renaming `globalEvents` to `global_events` to match other config options.
=> refactor: rename globalEvents to global_events

src/providers/starknet/utils.ts, test/unit/providers/starknet/__snapshots__/utils.test.ts.snap, test/unit/providers/starknet/fixtures.ts, test/unit/providers/starknet/utils.test.ts
When parsing nested structs we should pass index for current index within the struct. Previously it would pass index where its parent starts.
Test case makes sense (it used to return `{ high: '0x0', low: '0x23cdb7dc255bf4da' }` because it was reading choice as part of Uint256.
=> fix: pass local index when passing nested structs

src/graphql/index.ts, src/graphql/resolvers.ts, src/utils/database.ts, src/utils/graphql.ts
Closes https://github.com/snapshot-labs/checkpoint/issues/194
This PR adds special pluralization for metadata so it becomes querable again.
Alternatively we could use default pluralization (for database, still need it for GraphQL), but it will mean that DB schema will be different.
Run this query:
```gql
{
_metadatas {
id
value
}
_metadata(id: "last_indexed_block") {
id
value
}
}
```
=> fix: add special pluralization for metadata

src/checkpoint.ts, src/providers/base.ts, src/providers/starknet/index.ts, src/types.ts
Closes: https://github.com/snapshot-labs/checkpoint/issues/151
This PR adds support for optimistic indexing - now pending transactions are include when indexing. This option can be enabled with `optimistic_indexing` flag.
Assumptions:
- Writer will be called only once, either from pool or block, so writer needs to handle both scenarios if optimistic indexing is enabled.
- Pending transactions will be included in the next block (not +2 block)
- Pending transaction will always be included in the next block (can't fail/revert/disappear).
You can use this branch to test with: https://github.com/snapshot-labs/sx-api/tree/sekhmet/optimistic (remember to link this PR's checkpoint).
Not much difference is visible on goerli2 as it takes a while for transactions to show up in pending and block …
=> feat: add support for optimistic indexing

src/checkpoint.ts
Currently if errors occurs when processing blocks there is no feedback (other than seeing indexer process same block over and over).
We should log those errors so it's easy to see the issues.
- Test with https://github.com/snapshot-labs/sx-api/pull/177 by linking checkpoint
- Break something in the code, for example change `spaces` table name to `borked` in query to insert new proposal).
- Run `yarn dev` on sx-api.
- Errors get logged.
=> feat: log processing errors

src/knex.ts, src/stores/checkpoints.ts
Tests were actually failing for good reason, but I didn't pull latest master so I looked like CI issue.
This PR removes `mysql` usage in checkpoint's store that ended up there after merging two last PRs.
=> fix: convert resetStore to use knex

src/graphql/resolvers.ts
After knex refactor it's now called with toLowerCase() so it has to be defined.
=> fix: allow calling orderBy without orderDirection

src/checkpoint.ts, src/index.ts, src/orm/index.ts, src/orm/model.ts, src/register.ts
Depends on https://github.com/snapshot-labs/checkpoint/pull/212
This PR adds simple Model class that will be used as base for all generated models from schema.
What is missing:
- codegen to generate models from  GraphQL schemas (with this we probably could start make it public).
- transactions - all writes from writers should be batched into database transaction, together with call that updates current blockNumber so database stays consistent
- rollback support - with all requests going through ORM we can store data in DB that will allow us to revert inserts/update/deletes in case of rollbacks.
- Run this code: https://github.com/snapshot-labs/sx-api/compare/sekhmet/orm?expand=1
- Run `users` GraphQL query to make sure it works.
=> feat: add ORM Model

src/graphql/controller.ts, src/graphql/resolvers.ts, test/unit/graphql/__snapshots__/controller.test.ts.snap
Closes: https://github.com/checkpoint-labs/checkpoint/issues/215
This PR enables `contains` and `not_contains` filters support for Text types and enables `_nocase` variant for those filters for `String` and `Text`.
Run query like this:
```gql
{
proposals(where: {title_contains_nocase: "some"}) {
id
title
}
}
```
=> feat: add nocase support for contains string/text queries

src/checkpoint.ts, src/providers/starknet/index.ts
Currently, `processPool` is aborted if a single `getTransactionReceipt` throws. Instead, process the receipts that do get returned. It's quite common for a pending transaction receipt to be missing when hitting a cluster of nodes.
=> feat: continue fetching receipts on error

src/checkpoint.ts, src/providers/base.ts, src/providers/starknet/index.ts
This add the logic to define next block to sync in the provider directly within the `processBlock` function. This helps in some use case I'm testing where I sync a database which doesn't have blocks, in my setup a block is a transaction. But to sync the db it's not efficient to do it transaction per transaction I want to use batch of transaction instead. The issue is that if I use batch when I get close to have the db fully sync, I can not predict what will be the number of transaction available in the batch, by adding the next block within the provider `processBlock` function I can just return the last transaction order id to make sure the sync continue at the right transaction. There might be better approach to it but I found this to work well.
=> feat: receive next block number from processBlock

package.json, src/bin/index.ts, src/checkpoint.ts, src/codegen.ts, src/graphql/controller.ts, src/types.ts, src/utils/graphql.ts, test/unit/__snapshots__/codegen.test.ts.snap, test/unit/codegen.test.ts, yarn.lock
Closes: https://github.com/checkpoint-labs/checkpoint/issues/205
Depends on: https://github.com/checkpoint-labs/checkpoint/pull/230
This PR adds very primitive codegen for our ORM. This is exposed with `checkpoint codegen` script.
**BREAKING CHANGE: I had to move `decimalTypes` from runtime opts to CheckpointConfig as it needs to be defined statically so we can use it in scripts.**
- Build checkpoint.
- Go to some repo (for example [sx-api](https://github.com/snapshot-labs/sx-api/compare/sekhmet/codegen?expand=1) - this branch is converted to use ORM) that uses checkpoint and link checkpoint.
- Run `node path/to/checkpoint/dist/src/bin/index.js generate`.
- `.checkpoint/models.ts` should be generated.
- Try using models to interact with DB - if using sx-api from above repo is already …
=> feat: add codegen to generate ORM models from schema

src/checkpoint.ts, src/providers/base.ts, src/providers/starknet/index.ts, src/stores/checkpoints.ts, src/types.ts
Towards https://github.com/checkpoint-labs/checkpoint/issues/198
This PR adds verification that network returned by provider is the same as previously used.
- Start the server normally so network gets persisted.
- Change `network_node_url` in your config to different network.
- Start the server. You get error message.
- Set `resetOnConfigChange` to true in options, start server again, it continues.
- Remove this option, start server again, it works.
=> feat: add consistent network verification

src/stores/checkpoints.ts
Due to error we were truncating checkpoints table twice instead of checkpoints table and metadata table.
=> fix: truncate Metadata table

package.json, src/checkpoint.ts, src/stores/checkpoints.ts, src/utils/checkpoint.ts, yarn.lock
Depends on: https://github.com/checkpoint-labs/checkpoint/pull/232
Closes: https://github.com/checkpoint-labs/checkpoint/issues/198
This PR adds verification that tracked events didn't change.
- Start the server normally so start checksum gets persisted.
- Do some change in the config that you expect that should be detected (writer/abi names are not considered as they are user defined).
- Start the server. You get error message.
- Set `resetOnConfigChange` to true in options, start server again, it continues.
- Remove this option, start server again, it works.
=> feat: detect events and generic config changes

src/checkpoint.ts, src/graphql/controller.ts, src/providers/base.ts, src/providers/starknet/index.ts, src/stores/checkpoints.ts, src/types.ts, test/unit/stores/__snapshots__/checkpoints.test.ts.snap
We need to persist templates, otherwise when restarting the server it will continue processing blocks from last indexed block, but with information about executed templates it's likely to omit events.
- Start sx-api for ~100 blocks.
- Log `this.config.sources` here: https://github.com/checkpoint-labs/checkpoint/blob/c5e4deb22462b05b509e917277d11b8e884e988d/src/checkpoint.ts#L309
- Start sx-api without calling .reset (just .start())
- It should log both factory and one space in sources.
=> feat: persist templates

src/bin/index.ts
Closes: https://github.com/checkpoint-labs/checkpoint/issues/239
- Have repo in which you have Checkpoint beta.18 installed.
- In checkpoint repo run `yarn build`.
- Copy `dist/src/bin/index.js` from checkpoint to `node_modules/.bin/checkpoint` (this file should already exist, replace its contents) in other repo.
- Run `yarn checkpoint` in the other repo. It brings up help message.
=> fix: add missing shebang to cli entrypoint

src/checkpoint.ts, src/providers/starknet/index.ts
Previously sources added at transaction A would not be processed at that transaction, only when next transaction is processed.
This PR changes this behaviour causing new sources to be processed immediatelly, within the same transaction they were created (assuming start block expects this).
=> feat: process new sources events in same transaction

src/graphql/controller.ts, src/graphql/resolvers.ts, test/unit/graphql/__snapshots__/controller.test.ts.snap
Depends on https://github.com/checkpoint-labs/checkpoint/pull/246
This PR adds support for filtering entities by their subentities, for example following query becomes now possible:
```gql
{
spaces (where: { metadata_: { name_contains: "Shadow DAO"}}) {
id
metadata {
id
name
executors
executors_types
}
voting_delay
}
}
```
Test against https://github.com/snapshot-labs/sx-api/pull/181
=> feat: add nested entity filters

src/graphql/controller.ts, test/unit/graphql/__snapshots__/controller.test.ts.snap
Vote IDs do not fit as they have 2 Starknet addresses + proposal ID
=> feat: increase ID length to 256

src/graphql/resolvers.ts
Allows querying fields like this
```
authenticators: String[]!
```
Can be tested with https://github.com/snapshot-labs/sx-api/pull/186
=> fix: handle non-nullable List types

src/codegen.ts, test/unit/__snapshots__/codegen.test.ts.snap
JSON fields have to be encoded when saving on PostgreSQL. We already encode them when set manually, but don't when we get those values from database on load.
- Use [this PR](https://github.com/snapshot-labs/sx-api/pull/186) with PostgreSQL.
- Link and regenerate models with  `node ../checkpoint/dist/src/bin/index.js generate`. (you need to do it with bin file directly, `yarn checkpoint generate` won't work.
=> fix: encode JSON fields on load

src/checkpoint.ts, src/providers/base.ts, src/providers/starknet/index.ts, src/schemas.ts, src/stores/checkpoints.ts, src/utils/helpers.ts, test/unit/utils/helpers.test.ts
Closes: https://github.com/checkpoint-labs/checkpoint/issues/168
Closes: https://github.com/checkpoint-labs/checkpoint/issues/185
Closes: https://github.com/checkpoint-labs/checkpoint/issues/200
This PR adds prefetch for events, making it possible to only fetch blocks we know we have blocks for. Prefetch will speed up catching up to latest block (-50) by fetching events from 100 blocks at the time, and storing them in database, from where they are queried by normal indexing process to find events from source contracts. Old unused events are later purged.
You can test it by running it as usual, no extra changes on consumer side should be needed - it should just be much faster at finding new events.
=> feat: add prefetch for blocks

src/graphql/resolvers.ts, src/utils/graphql.ts
Closes: https://github.com/checkpoint-labs/checkpoint/issues/258
This PR fixes two issues:
- When querying non-nullable nested field in where prevents crash.
- When using nested where resolve objects and lists of scalars.
Run query like this on sx-api:
```gql
{
votes(where: {space_: {}}) {
space {
id
metadata {
id
name
executors
}
}
}
}
```
=> fix: make sure data from where clause is complete

src/graphql/controller.ts, test/unit/graphql/__snapshots__/controller.test.ts.snap
We need to make it compatible with TheGraph so we can use single query across Checkpoint and TheGraph.
=> feat: rename OrderBy type name to match TheGraph

src/graphql/controller.ts, src/graphql/resolvers.ts
Depends on: https://github.com/checkpoint-labs/checkpoint/pull/268
Addresses: https://github.com/checkpoint-labs/checkpoint/pull/268#issuecomment-1748812601
If nullable entity type's ID field is set to null we should return null on entity.
I'm not sure if it fixed issue with `The loader.load() function must be called with a value, but got: undefined.` as I couldn't find a way to reproduce.
=> fix: handle nested entity id set to null

src/stores/checkpoints.ts
If there are multiple contracts checkpointed at same block, this block can then be processed multiple times causing issues.
=> fix: select checkpoint blocks by distinct

src/providers/starknet/index.ts
We've seen cases of pool transactions being processed multiple times. It's possible to happen if RPC node returns outdated transactions from pool. We only cache seen pool transactions for single block, so if new block is minted but RPC returns pool before that block it could trigger twice.
Now we cache all processed transactions - this should be managable memory wise and prevent it from ever happening.
=> feat: prevent processing same transaction twice

src/providers/starknet/index.ts
Currently we fetch receipt of each transaction that is in pending block on every tick, even if we already saw this transaction before.
This is causing lots of requests as block can have ~400 transactions sitting in it for minutes and we hit it every 2 seconds.
Now instead of fetching those and skipping this in handlePool we skip those before they are even fetched.
=> fix: prevent fetching pool transactions every tick

src/checkpoint.ts
Currently when using seed checkpoints main loop will start syncing from those seeded blocks, but optimistic loop will prefetch block starting with star block, ignoring all seeds.
This PR addresses it so LastPrefetchedBlock will be adjusted when `seedCheckpoints` is called.
=> fix: start prefetch on last seeded block

src/codegen.ts, src/graphql/controller.ts, src/graphql/resolvers.ts, src/utils/graphql.ts
Currently you can define one-to-many relations using @derivedFrom directive. Using it the field on the entity is just virtual field that gets filled in at query time using lookup on the derived entity's column.
This PR adds support for non-derived one-to-many relations - this field needs to be filled in by writers to be usable. You specify ID's of referenced entity and those will be filled in with full object at query time.
=> feat: add support for non-derived one-to-many relations

src/checkpoint.ts, src/providers/base.ts, src/providers/starknet/index.ts, src/schemas.ts, src/stores/checkpoints.ts, test/unit/stores/__snapshots__/checkpoints.test.ts.snap
Closes: https://github.com/snapshot-labs/pitches/issues/75
This PR replaces old prefetch with new system that will load only events from contracts we are interested in.
This makes initial sync much faster (5 minutes instead of couple hours).
- Link this PR in `sx-monorepo` (also link `graphql` from `node_modules/graphql`) and build.
- Previous step might not work right away, if you get missing packages error when starting server nuke `node_modules` in both repos, reinstall and relink again - super inconsistent.
- Add `checkpoint.resetMetadata` before `reset` call.
- Start sx-api `NETWORK_NODE_URL=https://starknet-sepolia.infura.io/v3/AAAA NETWORK=SN_SEPOLIA yarn dev`
- Once synced (should take couple of minutes) check responses for some requests (for example all spaces with proposal/vote …
=> feat: prefetch blocks by targetting contracts

src/checkpoint.ts
Previously if optimistic indexing was not enabled every time
block is not found message would be displayed at ERROR level.
This PR prevents it from happening, only single info message
will be emitted.
=> chore: make logs less verbose in non-optimistic mode

src/graphql/resolvers.ts
Closes: https://github.com/checkpoint-labs/checkpoint/issues/296
Depends on: https://github.com/checkpoint-labs/checkpoint/pull/297
Test on this branch https://github.com/checkpoint-labs/checkpoint-template/compare/sekhmet/tt?expand=1
Run this query:
```gql
{
user(id: "a") {
id
}
users {
info {
id
}
}
}
```
First entity doesn't resolve, without this PR it would.
=> fix: only optimistically resolve nested entities

src/graphql/index.ts, src/graphql/resolvers.ts, src/stores/checkpoints.ts, src/utils/database.ts, test/unit/utils/database.test.ts
This commit also refactors out applyBlockFilter helper into database utils to avoid repetition.
Closes: https://github.com/checkpoint-labs/checkpoint/issues/301
Run query like this:
```gql
query ($checkpointId: ID!, $metadataId: ID!) {
spaces(block: 18407) {
id
}
_checkpoints {
id
}
_metadatas {
id
}
_checkpoint(id: $checkpointId) {
id
}
_metadata(id: $metadataId) {
id
}
}
```
It works without crashing.
=> fix: do not apply block range filter on internal tables

src/providers/starknet/provider.ts
- fix: Maximum call stack size exceeded with array.push (Bug: last_indexed_block reset to Zero after reaching the seed blocks #300)
When indexing contracts with a big number of events the array.push method will throw an error.
When you use spread operator all items of the source array are stored in the stack as arguments list, so having a large number of items (~ > 100K) will cause the this stack size exceed. The most simple work-around is to manually push all items one by one.
https://stackoverflow.com/questions/61740599/rangeerror-maximum-call-stack-size-exceeded-with-array-push
=> fix: Maximum call stack size exceeded with array.push

src/checkpoint.ts
If there are multiple events in single block we should only add one entry
into preloadBlocks. Otherwise it will cause `next` to be called multiple times
for the same block.
=> fix: deduplicate checkpoints

src/providers/starknet/provider.ts
Closes: https://github.com/checkpoint-labs/checkpoint/issues/308
In case of contracts that have lots of activity overall, but we only care about few events we should filter events by keys as well. This way we are not processing blocks that do not contain blocks that we are interested with.
1. Test with https://github.com/snapshot-labs/delegates-api/commits/fabien/multi-tokens/
2. It should be quick to sync (I only tested with NSTR token so it's quicker, currently testing with STRK, but it has lots of activity we are targeting so it won't be much faster).
=> feat: filter starknet events by event names

src/checkpoint.ts
When processing preloaded block and error happens we need to put it back into preloadedBlocks array (similar as with checkpoint block).
- Put `throw` in random writer (that isn't caught).
- It should keep retrying processing this block instead of progressing further.
=> fix: restore preloaded block on error

src/graphql/controller.ts
It was possible to create duplicate entires that would apply within the same block that would have single ID.
That shouldn't be the case, ID is not longer unique in whole table, but should be within single block_range.
=> fix: prevent duplicate entries with overlapping block_ranges

src/providers/evm/provider.ts
Similarly to https://github.com/checkpoint-labs/checkpoint/pull/302/files , fix the call stack size issue with `evm` provider
=> fix: maximum call stack in evm provider

src/graphql/resolvers.ts
When using nested where filter we should read field return type from that nested type, not top-level type.
- Same as https://github.com/checkpoint-labs/checkpoint/pull/319
- Plus run following query that was broken:
```gql
{
proposals(
where: {
cancelled: false
space_in: [
"0x03ced313394107c43a2f36b63262c00a6422231ac229dc4cedd0d9928d8c3c5f"
]
metadata_: { title_contains_nocase: "" }
}
) {
id
}
}
```
=> fix: read fieldType from currently processed type

package.json, src/checkpoint.ts, src/stores/checkpoints.ts
When we reset we will visit old blocks again so we need to clear previously stored ones to avoid conflicts.
=> fix: clear blocks on reset

src/codegen.ts, test/unit/__snapshots__/codegen.test.ts.snap, test/unit/codegen.test.ts
Arrays are stored as strings in the database so we have to initialize them as such as well.
=> fix: initialize arrays to string value

src/checkpoint.ts, src/stores/checkpoints.ts, test/unit/stores/__snapshots__/checkpoints.test.ts.snap, test/unit/stores/checkpoints.test.ts
With support for multiple indexers in single Checkpoint instance we have to accomodate for those in our database.
This commit makes necessary changes in our metadata store.
Currently checkpoint still supports single indexer, but now metadata can accomodate it.
1. Run checkpoint-template with this PR (you need to call `resetMetadata` before `reset`).
2. Run this query.
3. All looks good (we don't expose indexer in metadata on GraphQL yet, next PR).
```gql
{
posts {
id
content
tag
tx_hash
created_at_block
}
_metadatas {
id
value
}
}
```
=> feat: add indexer to metadata

package.json, src/graphql/resolvers.ts
Towards https://github.com/snapshot-labs/sx-monorepo/issues/997
Refactors: https://github.com/checkpoint-labs/checkpoint/pull/319, https://github.com/checkpoint-labs/checkpoint/pull/321
We can't precompute type because it's impossible to easily figure out what part of where filter is type and what is operator.
For example max_end_gte should be (max_end, gte), but authenticators_not_containts should be (authenticators, not_contains) so it can't be done with simple split, because pivot is moving around.
With sx-api run this query, no errors show up.
```gql
{
proposals(
where: {
cancelled: false
space_in: [
"0x03ced313394107c43a2f36b63262c00a6422231ac229dc4cedd0d9928d8c3c5f"
]
metadata_: { title_contains_nocase: "" }
max_end_gt: 0
}
) {
id
}
spaces(
where: {
authenticators_contains: [ …
```
=> fix: read type on-demand

src/checkpoint.ts, src/container.ts
This PR moves startup logic to container class. This change is internal only, no external API change happened.
Container **will** encapsulate indexer and separate it from main Checkpoint instance.
Right now it moves:
- `reset`/`resetMetadata` calls.
- `validateConfig` call.
- `validateStore` call.
- Helper methods like `getConfigStartBlock` and `getStartBlockNum` as those are used in container.
In the future entire logic for indexer will be encapsulated in Container. Checkpoint will only manage containers calling its life cycle methods (start/reset).
1. Use checkpoint-template.
2. Make sure `resetMetadata` is called before `reset`.
3. Comment out your writer.
4. Start server, you get error message about missing writer.
5. Restore writer.
6. Comment out `resetMetadata` in config.json …
=> refactor: move startup logic to per-indexer container

src/checkpoint.ts, src/container.ts, src/providers/base.ts, src/providers/evm/provider.ts, src/providers/starknet/provider.ts, src/types.ts
This PR moves lifecycle to container class. This change is internal only, no external API change happened.
This encapsulates indexer and separates it from main Checkpoint instance.
1. Use checkpoint-template.
2. Make sure `resetMetadata` is called before `reset`.
4. It indexes data as before.
=> refactor: move lifecycle logic to per-indexer container

package.json, yarn.lock
Within 5 version starknet makes some changes to exposed types which we depend on. We have to pin it to specific version for now to avoid issues with consumers having unsupported version.
=> chore: pin starknet

src/bin/index.ts, src/checkpoint.ts, src/codegen.ts, src/container.ts, src/graphql/controller.ts, src/graphql/index.ts, src/graphql/resolvers.ts, src/orm/model.ts, src/register.ts, src/schemas.ts, src/types.ts, src/utils/database.ts, src/utils/graphql.ts, test/unit/__snapshots__/codegen.test.ts.snap, test/unit/codegen.test.ts, test/unit/graphql/__snapshots__/controller.test.ts.snap, test/unit/utils/database.test.ts
Few forced changes for consumers:
- ORM now requires indexer to be specified to know which indexer entity belongs to.
- Things had to move around `CheckpointConfig`, `CheckpointsOptions` and `OverridesConfig` (new, used for database options, like decimals as it needs static config for ORM).
```ts
const mainnetConfig = createConfig('mainnet');
const sepoliaConfig = createConfig('sepolia');
const mainnetIndexer = new starknet.StarknetIndexer(createStarknetWriters('mainnet'));
const sepoliaIndexer = new starknet.StarknetIndexer(createStarknetWriters('sepolia'));
const checkpoint = new Checkpoint(schema, {
logLevel: LogLevel.Info,
prettifyLogs: true
});
checkpoint.addIndexer('mainnet', mainnetConfig, mainnetIndexer);
checkpoint.addIndexer('sepolia', sepoliaConfig, sepoliaIndexer);
```
- Test …
=> feat: add support for multi chain indexing

src/schemas.ts, src/types.ts, src/utils/logger.ts
This way we get annotations for (some of) our types:
=> chore: replace simple comments with jsdoc

src/checkpoint.ts
Options should be shared across all containers (they are currently, if you pass options to addIndexer only resetOnChange will be respected, other values are used from main options.
=> refactor: reuse instance options for all containers

src/bin/index.ts, src/checkpoint.ts, src/codegen.ts, src/graphql/controller.ts, test/unit/codegen.test.ts, test/unit/graphql/__snapshots__/controller.test.ts.snap, test/unit/graphql/controller.test.ts
Full query schema will be useful for integrating into UI without the need of getting schema from running API instance.
Run `node PATH_TO_CHECKPOINT/dist/src/bin/index.js generate` in API and it should generate `.checkpoint/schema.gql`.
=> feat: add schema generation as codegen step

package.json, src/graphql/controller.ts, src/graphql/resolvers.ts
On SX API we migrated to use non nullable lists in schema, for example [Space!]! but this means we need to unwrap those to get actual type.
=> fix: unwrap non-null types

package.json, src/container.ts, src/stores/checkpoints.ts
Previously it would try to revert all entries breaking other indexer's state.
It looks like it was the issue that caused state of one indexer to get nuked (some entries being removed, some ending up as empty) sometimes when running multiple indexers.
=> fix: on reorg only revert reorganized indexer

src/providers/evm/provider.ts, src/providers/starknet/provider.ts
Previously we threw and cought our own errors immediatelly, in case of EVM Reorg/NoBlock and in case of Starknet Reorg errors would result in getting block failed... retrying log messages.
=> fix: do not catch custom Reorg/NoBlock errors

package.json, src/providers/evm/provider.ts, src/providers/starknet/provider.ts
This PR will cache computed event hashes for our sources as well as use faster EVM address comparison (that doesn't add checksum as those are bit expensive).
=> perf: reduce computations related to event hashes and address comparisons

src/container.ts
This adds ability to revert to preload if sequential indexing ends up falling behind. We check latest block every 50 blocks and if if it's more than BLOCK_PRELOAD_OFFSET * 2 ahead of us preload will be activated again.
1. Run with SX API.
2. Change ARB1 start block to 312004031.
3. Run it as `ENABLED_NETWORKS=arb1 yarn dev`.
4. You will see it starts with preload, then it switches to sequential indexing.
5. After a while latest block check fires and you get info how behind we are.
6. If we are more than 100 blocks behind you will see message we are reverting to preload.
7. Preloading happens.
8. Now we are going sequential as well with less than 100 blocks behind.
=> feat: allow reverting to preload if fallen behind

package.json, src/container.ts
`getBlockHash` can fail so we need to handle this and retry.
=> fix: handle errors in handleReorg

package.json, src/graphql/index.ts, src/graphql/resolvers.ts, src/utils/database.ts
This change introduces stable ordering for entities - as last step (after user defined orderBy) entries will be ordered by block_range.
This makes it stable as SQL doesn't make any guarantees about order unless ORDER BY is used.
=> fix: sort by block_range by default

.github/workflows/build-test.yml, .github/workflows/release.yml, package.json, src/orm/model.ts
When deleting entry we should only update latest entry, otherwise if entity has multiple versions (it was edited) it will update every one of them, so they will end up having the same (id, indexer, block_range) making it non-unique.
=> fix: only update latest entry on delete

src/container.ts
Previously we used alphanumeric sort which could return unexpected result (for example 1, 2, 11) would be sorted as (1, 11, 2).
=> fix: use numeric sort for preloaded blocks

package.json, src/container.ts, src/providers/base.ts
Recursive calls (without termination like we did before) can lead to exceeding maximum call stack size. Instead we use loop.
This will additionally reduce memory usage as stack won't grow indefinitely.
1. Use it as normal, it works as expected. I tested it by syncing up `sep` and `sn-sep` on SX-API and it worked as expected.
=> refactor: remove recursive call when processing blocks

package.json, src/providers/evm/provider.ts, src/providers/evm/types.ts, src/providers/starknet/provider.ts, src/providers/starknet/types.ts
If event don't come from preload it means we have every event from it, meaning twe don't need to fetch missing ones.
1. Run sx-api with this version starting with latest block on sepolia.
2. Create space on Ethereum Sepolia.
3. Space gets indexed properly (previously it would get stuck there).
=> fix: only refetch missing events if block comes from preload

src/providers/evm/helpers.test.ts, src/providers/evm/helpers.ts, src/providers/evm/provider.ts, src/providers/evm/types.ts
Closes: https://github.com/snapshot-labs/workflow/issues/639
We had case of RPC using Infura-like range hint, but from/to were either missing or not using hex format which resulted in our code setting itself to NaN.
Now we validate those values are finite.
We also include new Ankr size hint.
=> fix: validate block range hint

package.json, yarn.lock
This version is compatible with GraphQL v16 (it already was before,
but it wasn't listed in peerDependencies).
=> chore: bump graphql-parse-resolve-info

src/providers/evm/provider.ts
I've seen some weird behavior. Possibly it could be some provider suggesting range that moves from back into the past, but we don't have logs to verify that.
=> feat: add log message on RPC range hints

package.json, src/providers/evm/provider.ts, src/providers/evm/types.ts, yarn.lock
Closes: https://github.com/snapshot-labs/workflow/issues/611
This PR ports EVM provider from ethers.js v5 to viem.
This brings some quality of live improvements.
Now calls made using viem client have 5s timeout. The same timeout is used in `getLogs` request when requesting logs by `blockHash` (single block request).
This should prevent issue of live syncing stopping due to hanging requests which we have experienced.
Timeout is not applied in preload stage as those requests tend to have long response times.
Now parsed events in writers can be fully typed. This requires constant JSON ABI. To enable this you can type your writers like this:
```typescript
const writer: evm.Writer<typeof MyAbi, 'someEvent'> = ({ event }) => {
if (!event) return
event.args.id
//    ^? - this is now typed using …
```
=> refactor(evm): port EVM provider to viem
